name: CounterCulture
favicon: null
layout_spectrum: 0.53699
typography_spectrum: 0.53292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f0'
    - '#878787'
    - '#575757'
    - '#00a8f9'
    - '#0473f9'
  brandStrength: 0.5625
  lightness: 0.5775690383743495
  saturation: 0.5839356374926865
  rhythmicContrast: 0.5528455344028771
purpose: []
